#!/usr/bin/env python3
import argparse

from argo_probe_htcondorce.htcondorce_certvalidity import timeout, \
    validate_certificate


def main():
    parser = argparse.ArgumentParser(
        description="ARGO probe for checking HTCondorCE certificate validity"
    )
    parser.add_argument(
        "--user_proxy", dest="user_proxy", type=str, required=True,
        help="path to X509 user proxy"
    )
    parser.add_argument(
        "-H", "--hostname", dest="hostname", type=str, required=True,
        help="hostname"
    )
    parser.add_argument(
        "-t", "--timeout", dest="timeout", type=int, default=60, help="timeout"
    )
    parser.add_argument(
        "--ca-bundle", dest="ca_bundle", type=str, required=True,
        help="location of CA bundle"
    )
    args = parser.parse_args()

    with timeout(seconds=args.timeout):
        validate_certificate(args)


if __name__ == "__main__":
    main()
